TYPE
	PM : 	STRUCT  (*Type structure for pump*)
		i_ao : INT; (*Analog Output*)
		r_ist : REAL; (*Actual volume flow in kg/h*)
		r_soll : REAL; (*Set volume flow in kg/h*)
		r_min : REAL; (*Minimum control value in kg/h*)
		r_max : REAL; (*Maximum control value in kg/h*)
		pfm_width : REAL; (*Pulse width (for digital pulse control)*)
		pfm_width_act : REAL; (*Pulse width (for digital pulse control) - current value*)
		pfm_pause : REAL; (*Minimum pause between pulses (for digital pulse control)*)
		pfm_pause_act : REAL; (*Minimum pause between pulses (for digital pulse control) - current value*)
		pfm_duty : REAL; (*Pulse frequency (0=No pulse/Continuous pause, 100=Continuous pulse/No pause)*)
		b_update : BOOL; (*Update of parameters (PID control parameters)*)
	END_STRUCT;
	MFC : 	STRUCT  (*Type structure for mass flow controller measurement and set values*)
		i_ai : INT; (*Analog Input - Measurement value*)
		i_ao : INT; (*Analog Output*)
		r_ist : REAL; (*Actual volume flow in Nl/min*)
		r_soll : REAL; (*Set volume flow in Nl/min*)
		r_min : REAL; (*Minimum measurement/control value in Nl/min*)
		r_max : REAL; (*Maximum measurement/control value in Nl/min*)
	END_STRUCT;
	PRES : 	STRUCT  (*Type structure for pressure measurement values*)
		i_ai : INT; (*Analog Input*)
		r_ist : REAL; (*Actual pressure value in bar (relative)*)
		r_ist_avg : REAL; (*Moving average of the pressure over a specified time*)
		r_ist_abs : REAL; (*Actual pressure value in bar (absolute)*)
		r_soll : REAL; (*Set pressure value in bar (relative)*)
		r_min : REAL; (*Minimum measurement value in bar (relative) [for PIR7: bar (absolute)]*)
		r_max : REAL; (*Maximum measurement value in bar (relative) [for PIR7: bar (absolute)]*)
	END_STRUCT;
	TEMP : 	STRUCT  (*Type structure for temperature measurement values*)
		i_at : INT; (*Analog AT module measurement value*)
		r_ist : REAL; (*Actual temperature value*)
		r_ist_avg : REAL; (*Moving average of the temperature over a specified time*)
		r_soll : REAL; (*Set temperature value*)
	END_STRUCT;
	GA : 	STRUCT  (*Type structure for gas analysis measurement values*)
		i_ai : INT; (*Analog Input*)
		r_ist : REAL; (*Measurement value: Volume concentration [-]*)
		r_max : REAL; (*Maximum measurable volume concentration [-]*)
		r_min : REAL; (*Minimum measurable volume concentration [-]*)
	END_STRUCT;
	RV : 	STRUCT  (*Type structure for process control valve characteristics*)
		i_ao : INT; (*Analog Output (valve position)*)
		r_open_min : REAL; (*Minimum valve opening degree (opening degree = 0 corresponds to 0% open)*)
		r_open_max : REAL; (*Maximum valve opening degree (opening degree = 100 corresponds to 100% open)*)
		b_update : BOOL; (*Update of valve position*)
	END_STRUCT;
	NA : 	STRUCT  (*Type structure for emergency stop signal input and output*)
		b_do : BOOL; (*DO signal - Software emergency stop activation*)
		b_di : BOOL; (*DI signal - Signal to control in case of emergency stop*)
	END_STRUCT;
	VOLF : 	STRUCT  (*Type structure for volume flow values*)
		m3_s : REAL; (*in m³/s*)
		l_min : REAL; (*in l/min*)
		m3_h : REAL; (*in m³/h*)
	END_STRUCT;
	TB : 	STRUCT  (*Type structure for temperature limiter*)
		i_ai : INT; (*Analog Input*)
		r_ist : REAL; (*Actual temperature value*)
		r_min : REAL; (*Minimum measurement value*)
		r_max : REAL; (*Maximum measurement value*)
	END_STRUCT;
	LIRC : 	STRUCT  (*Type structure for level control*)
		r_ist : REAL; (*Actual level value in cm*)
		r_ist_avg : REAL; (*Moving average of the level in cm over a specified time*)
		r_soll : REAL; (*Set level value in cm*)
	END_STRUCT;
	PV : 	STRUCT  (*Type structure for proportional valves*)
		i_ao : INT; (*Analog Output (valve position)*)
		r_ist : REAL; (*Valve opening degree*)
		r_open_min : REAL; (*Minimum valve opening degree (opening degree = 0 corresponds to 0% open)*)
		r_open_max : REAL; (*Maximum valve opening degree (opening degree = 100 corresponds to 100% open)*)
		b_update : BOOL; (*Update of parameters (PID control parameters)*)
	END_STRUCT;
END_TYPE
